import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../services/auth.service';

@Component({
  // tslint:disable-next-line:component-selector
  selector: '', // Generated by app.routes.ts
  templateUrl: './app-welcome.component.html',
  styleUrls: ['./app-welcome.component.css']
})
export class AppWelcomeComponent implements OnInit {

title: string;

  constructor( private auth: AuthService) {
    this.title = 'Sharing Votes';
}

  ngOnInit() {
  }

  login() {
    this.auth.login();
  }

}
